### ISSUE TITLE
Got wrong mac address on MacOs

### ISSUE THREAD

**Issue by lulinchuanllc** [repnop/mac_address#40]
<img width="728" alt="企业微信截图_cde313c6-f8e3-4871-be5d-d4e2e8340e8d" src="https://github.com/repnop/mac_address/assets/15902845/d1e65753-8072-421f-8d41-8ff2d2d3a91c">

It return a mac address of interface "anpi1" or "anpi0" which should be "en0", because neither "anpi0" and "anpi1" are actived

**Comment by capveg-netdebug** [comment]
I'm new here so take this with a grain of salt, but my reading of the API (and code) is that get_mac() will return *any* MAC address on the system -- so I think this is just 'working as expected'.  I've just added #42 with get_mac_address_by_ip() which allows you to get a more specific mac and hopefully solves your problem.

Good luck.

**Comment by repnop** [comment]
> I'm new here so take this with a grain of salt, but my reading of the API (and code) is that get_mac() will return _any_ MAC address on the system -- so I think this is just 'working as expected'. I've just added #42 with get_mac_address_by_ip() which allows you to get a more specific mac and hopefully solves your problem.
> 
> Good luck.

A better solution would probably be to look up the MAC by name if you already know what it is, which is already possible.

---

I'll have to look into seeing how the status of an interface is exposed on the various platforms, because otherwise yes this is working as intended, but getting the first "active" MAC could be something added in the future

**Comment by repnop** [comment]
closing as stale
